import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from './provider/Web3Provider';
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          {children}
          <footer className="py-6 bg-gray-100 border-t border-gray-200">
            <div className="container mx-auto px-4 sm:px-6 lg:px-8 text-center text-gray-500 text-sm">
              &copy; {new Date().getFullYear()} Doneth. All rights reserved.
            </div>
          </footer>
        </body>
      </Providers>
    </html>
  );
}
